run:
  timeout: 5m
linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-specific: false
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gci
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - revive
    - rowserrcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
